const express = require('express');

const usersRoutes = require('./users.routes');
const contactInfosRoutes = require('./contactInfos.routes');
const schoolsRoutes = require('./schools.routes');
const teachersRoutes = require('./teachers.routes');
const studentsRoutes = require('./students.routes');
const formationsRoutes = require('./formations.routes');
const studentGroupsRoutes = require('./studentGroups.routes');
const schoolUsersRoutes = require('./schoolUsers.routes');
const userContactInfosRoutes = require('./userContactInfos.routes');
const studentRegistrationsRoutes = require('./studentRegistrations.routes');
const teacherRegistrationsRoutes = require('./teacherRegistrations.routes');
const authRoutes = require('./auth.routes');
const schoolSetupRoutes = require('./schoolSetup.routes');
const dashboardRoutes = require('./dashboard.routes');
const classroomsGroupsRoutes = require('./classroomsGroups.routes');
const promoCodesRoutes = require('./promoCodes.routes');
const weeklyProgramRoutes = require('./weeklyProgram.routes');
const attendanceRoutes = require('./attendance');
const studentSpaceRoutes = require('./studentSpace.routes');
const teacherSpaceRoutes = require('./teacherSpace.routes');
const notificationsRoutes = require('./notifications.routes');
const paymentHistoryRoutes = require('./paymentHistory.routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/school-setup', schoolSetupRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/users', usersRoutes);
router.use('/contact-infos', contactInfosRoutes);
router.use('/schools', schoolsRoutes);
router.use('/teachers', teachersRoutes);
router.use('/students', studentsRoutes);
router.use('/formations', formationsRoutes);
router.use('/student-groups', studentGroupsRoutes);
router.use('/school-users', schoolUsersRoutes);
router.use('/user-contact-infos', userContactInfosRoutes);
router.use('/student-registrations', studentRegistrationsRoutes);
router.use('/teacher-registrations', teacherRegistrationsRoutes);
router.use('/promo-codes', promoCodesRoutes);
router.use('/weekly-programs', weeklyProgramRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/student-space', studentSpaceRoutes);
router.use('/teacher-space', teacherSpaceRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/payment-history', paymentHistoryRoutes);
router.use('/', classroomsGroupsRoutes);

module.exports = router;